### ISSUE TITLE
[Feature Request] some thoughts on trojan

### ISSUE THREAD

**Issue by cattyhouse** [trojan-gfw/trojan#148]
- [x] I certify that I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

### if trojan runs on 0.0.0.0:443

1. still need some http server program to listen on 80 (nginx alike)
2. need to reload trojan after certification renew, this is ok and can be done by certbot hook
3. trojan runs as nobody, but certifications generated by certbot usually have strict permission settings, need extra code to cp, chmod and chown certs and keys on the first time setup as well as when certifications get renewed. 
4. if trojan exit abnormally due to bugs or whatever reason, the websites run by nginx on this server will all be down. 

I wonder if anything you could do to make these processes easier? 

### if trojan runs behind nginx

1. this could be easier as nginx will handle certs and keys permission anytime including renew and it also handle the 80 listening. because nginx is started as root but after that run as a normal user. 
2. but there is no document on how to do this.

### differences 

1. are there any "security | performance" differences between trojan running in front and behind nginx?

**Comment by GreaterFire** [comment]
Thanks for your suggestions.

If trojan runs on `0.0.0.0:443`:
1. This is intentional so trojan can forward illegal traffic to any service you want, not just HTTP. Or you can just don't forward it at all.
1. Trojan supports gracefully reloading certificate without interrupting existing connections by `SIGUSR1`.
1. You can modify the systemd service to make trojan run as another user who has the permission to read the certificate.
1. You can setup proper monitoring to re-launch trojan when it crashes.

You can, in fact, setup trojan behind nginx (#131) but it's not trivial. There is no plan currently to change the mechanism of how trojan works at this point. If you have strong opinion on it, you can fork trojan and modify it as you want or write your own tool.

**Comment by cattyhouse** [comment]
"You can, in fact, setup trojan behind nginx (#131) but it's not trivial."

It would be really helpful if you could give an example config to let nginx, v2ray (ws+tls), trojan work together. thank you. 

I have another question: if people request www.xxx.com:80, what would trojan react?

**Comment by itshaadi** [comment]
> I have another question: if people request [www.xxx.com:80](http://www.xxx.com:80), what would trojan react?

it does nothing, in that case you are directly connected to nginx on port 80.

you could redirect port 80 to 443, and serve the content on `127.0.0.1:8080` then configure trojan to reach 8080 instead of 80, this way everything always goes through trojan.

I also created an [automation script](https://github.com/itshaadi/trojan-autoconf/) that might help you as well (forget the diagram I have to change it to demonstrate https://github.com/itshaadi/trojan-autoconf/commit/f526df27f39b5a6dad0040fca36006fc5ecadac1)

**Comment by cattyhouse** [comment]
@itshaadi thanks for your solution, it is a good idea to listen on other port other than 80, in this case, 80 can be redirect to 443 as usual, while trojan can redirect other protocol to 8080. that's awesome!
