### ISSUE TITLE
async_read_some function

### ISSUE THREAD

**Issue by JimZhangIress** [trojan-gfw/trojan#188]
from boost::asio documentation, seems async_read_some function may not read complete message, however seems we never handle this in case we only read partially? Thanks.

The read operation may not read all of the requested number of bytes. Consider using the async_read function if you need to ensure that the requested amount of data is read before the asynchronous operation completes.

**Comment by GreaterFire** [comment]
Thank you for your insightful review of the code! This software is designed under the assumption that the trojan header will be read in one call since it's so short (around 100 bytes), and this assumption works pretty well. If there will be any problems in the future, I'll change the logic of reading data from sockets.
