### ISSUE TITLE
[Question] SSH Compatible

### ISSUE THREAD

**Issue by GF-Huang** [trojan-gfw/trojan#196]
According to [the docs of protocol](https://trojan-gfw.github.io/trojan/protocol):

> When the server receives the first data packet, it checks if the hashed password is correct and the Trojan Request is valid. If not, the protocol is considered “other protocols” (see next section). **Note that the first packet will have payload appended.** This avoids length pattern detection and may reduce the number of packets to be sent.

I have never read the source code of trojan, but I am curious if this is compatible with the SSH protocol? The SSH protocol handshake would be "the server send data to client first", ranther then "client send to server first".

**Comment by GreaterFire** [comment]
@GreatFireWall Good question!

The behavior of my implementation is:
The client will simultaneously wait for the first client payload and connection to the trojan server. If the first payload happens first, then the trojan request will contain the first payload, otherwise (the connection to the server is established before the first payload arrives) it will not.

**Comment by GF-Huang** [comment]
If the `trojan server` do not connect to the `real target server` before it received the first payload from `trojan client`, the `trojan client` will never receive the SSH server(real target server)  handshake packet.

**Comment by GreaterFire** [comment]
@GreatFireWall I don't quite understand your claim here. Trojan works pretty fine with SSH right now. Try to understand the state machine yourself by looking at the code or just try the software yourself

**Comment by GF-Huang** [comment]
OK, thanks.
