### ISSUE TITLE
URLs under Content are missing *.md

### ISSUE THREAD

**Issue by j3ffyang** [trojan-gfw/trojan#31]
For example, [https://github.com/trojan-gfw/trojan/blob/master/docs/config](https://github.com/trojan-gfw/trojan/blob/master/docs/config) should be [https://github.com/trojan-gfw/trojan/blob/master/docs/config.md](https://github.com/trojan-gfw/trojan/blob/master/docs/config.md). And so are other URLs. Regards.

**Comment by GreaterFire** [comment]
Thank you for your issue. This is intended so that GitHub Pages works normally. Jekyll converts Markdown scripts to html and **removes** the `.md` suffix.

You can experiment with it yourself:

- https://trojan-gfw.github.io/trojan/protocol
- https://trojan-gfw.github.io/trojan/protocol.md

They make a difference.
