### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by wobud** [trojan-gfw/trojan#311]
I find out a problem which may expose the identity of the server.

If I supply a wrong password in the Igniter deliberatelly, and next step visit a website in chrome, a"400 bad request nginx" error is returned.

If I supply in the remote address a domain which I know doesnt have trojan running on it, a different result is returned..

**Comment by Chigusa0w0** [comment]
@wobud It has nothing to do with what HTTP Server you are using on your Trojan server. __It related to which one is deployed on the irrelevant website.__ Please check whether accessing `http://example.com` with Trojan config `remote=apache.org:443`, a site using Apache, `remote=www.iis.net:443`, a site using IIS, and `remote=lwan.ws:443`, a site using Lwan, will trigger the download or not. If yes, could you upload the file downloaded and state your environment information for further investigation?

According to my test, a friendly 400 will be shown when you try accessing to `example.com` with all above mentioned config. Proving the issue is a Nginx specific bug.

**Comment by wobud** [comment]
The case is what as you said.Nothing was downloading.

But my trojan server which runs Apache gives back a somewhat different result as apache.org, revealing my server is listening local 127.0.0.1 80 port. See the pics attached.
![mmexport1583898147987](https://user-images.githubusercontent.com/62016165/76380337-7b655b00-638d-11ea-975a-e396e2f7aa8d.jpg)
![mmexport1583898152397](https://user-images.githubusercontent.com/62016165/76380346-7e604b80-638d-11ea-858e-dbef3e872d0d.jpg)

**Comment by Chigusa0w0** [comment]
@wobud For port display. It is not a Trojan related issue.

**Comment by wobud** [comment]
@LimiQS I think so.Maybe I should do some changes in the Apache files to get it solved.

**Comment by wobud** [comment]
Everything is Okay for me now.Turn the server signature off in default.conf.
Trojan is really a great project and especially a great idea.
I recommend not to use nginx to power the disguise site for the moment.
