### ISSUE TITLE
Can you add database support for Sqlite3?

### ISSUE THREAD

**Issue by zdm2008** [trojan-gfw/trojan#353]
Can you add database support for Sqlite3?

**Comment by GreaterFire** [comment]
It was carefully chosen whether to use MySQL or SQLite 3 as our database backend. It turned out that because SQLite 3 has worse library support, cannot work across machines, and it doesn't support multiple processes connecting to the same file, we chose MySQL and do not have plans to support SQLite 3.

Currently, I don't want to introduce yet another dependency (SQLite 3) to trojan, so I will not implement this feature. Sorry.

**Comment by GreaterFire** [comment]
For our feature request policy, see [CONTRIBUTING.md](https://github.com/trojan-gfw/trojan/blob/master/CONTRIBUTING.md).
