### ISSUE TITLE
[Bug report] Trojan转发正常的nginx流量的时候能否带上用户真实ip

### ISSUE THREAD

**Issue by niostack** [trojan-gfw/trojan#377]
我的trojan的配置是：

> {
>     "run_type": "server",
>     "local_addr": "0.0.0.0",
>     "local_port": 443,
>     "remote_addr": "127.0.0.1",
>     "remote_port": 80,
>     .......省略

然后我的nginx站点配置直接监听80端口，**但是问题是nginx的日志中$remote_addr 字段永远都是本地ip地址：127.0.0.1**；而我想要的是nginx日志中能得到用户的真实ip，请问有解决方案吗？

**Comment by GreaterFire** [comment]
There is no solution to this. Since trojan isn't an HTTP reverse proxy (because it supports forwarding any TCP protocol), it doesn't add `X-Forwarded-For` in the HTTP header. There is no other ways NGINX can get the real IP.

If you really want the real IP, you can check out trojan's log, and correspond the connections there with those in your NGINX log.
