### ISSUE TITLE
After actual testing, trojan is too slow

### ISSUE THREAD

**Issue by garywu520** [trojan-gfw/trojan#43]
Profile has opened TFO and BBR, After actual testing, trojan is too slow。。。

配置文件打开了TFO和BBR，然而速度慢成了翔，有没有参数提供下优化？

**Comment by Zxilly** [comment]
这个英文和中文语气差的有点大啊。。。

**Comment by garywu520** [comment]
@Zxilly 以英文为准...中文算是吐槽...

**Comment by GreaterFire** [comment]
Please define how slow is "slow as shit".

**Comment by garywu520** [comment]
连接后日志显示正常，无错误。网页打开后，明显感觉停顿3-4秒才能显示网页内容，甚至更长时间。貌似SSL加解密需要时间的感觉。YouTube 视频144p基本打不开

**Comment by GreaterFire** [comment]
Did you compare the results with other tools and/or servers?

In my experiments, trojan can get up to 60 Mbps (my bandwidth limit, in theory it can get up to your bandwidth limit) across GFW.

The encryption/decryption overhead can be ignored, since on local tests, the max speed is 10 Gbps.

Please provide your cloud service provider for further analysis.

**Comment by garywu520** [comment]
已排除DNS污染问题，调试一些参数后，测试问题依旧。有几个问题需要确认下：

1. forward.json 中转是否可以不用配置，client直接连接server【我目前测试采用的是这种方式】
2. SSL证书是否有强制要求，比如必须是购买的认证证书？【我测试使用的是openssl自签名证书】

**Comment by GreaterFire** [comment]
I typically do not discuss this kind of user issues on GitHub. Could you provide other means of communication so I can reach you more conveniently?

**Comment by wuyanteng** [comment]
TG:  @GaryWu520

Thanks  you

**Comment by wuyanteng** [comment]
Gmail:    wuyanteng520@gmail.com

**Comment by GreaterFire** [comment]
Contact info redacted for security reasons.

Issue resolved.

**Comment by zshuker** [comment]
trojan.exe闪退

**Comment by GreaterFire** [comment]
@zshuker Please run trojan inside a cmd to see what error it is.
