### ISSUE TITLE
可能存在的漏洞

### ISSUE THREAD

**Issue by 960PRO** [trojan-gfw/trojan#441]
Trojan团队，你们好。隔壁V2ray爆出严重漏洞https://github.com/v2ray/v2ray-core/issues/2523
这种漏洞可能影响Trojan，请排查一下Trojan是否有这种缺陷。
谢谢，致敬你们这些开发者。

**Comment by MirrorCubeSquare** [comment]
English Translation：
due to bug report from V2RAY-core
Vmess+TCP is now under serious vulnerability
Such bug may affect Trojan as it touches the basic design of any anti-GFW method
thx

如果我云两边的说明书以及对面的issue没错的话，目前的情况是这样
vmess早就是个筛子，只不过现在可以彻底宣告非TLS的vmess退休了
而trojan从原理上（在流量形态上）大致相当于v2ray的WS+TLS实现（只不过在tls层后没有vmess的混淆保护）
所以目前来看只要tls是安全的，trojan方案和VMess+TLS方案暂时还是安全的
（虽然在这种情况下TLS加的这个Vmess还有没有意义是个问题）

参考https://github.com/trojan-gfw/trojan/issues/14
trojan的整体设计上将对抗安全性全面依赖于tls上，而v2ray的issue内讨论也在说基于TLS全面重写VMess

啰嗦一下的总结
1）目前Trojan的安全没有受到影响（由于外层TLS的可靠性）
2）Trojan从一开始也不打算对内层（Trojan指令包）进行安全性设计
3）用V2Ray那边的讨论的话就是：自己设计一万个轮子（VMess）不如直接采用目前的最佳设计（all in TLS）

**Comment by GreaterFire** [comment]
@960PRO No. We don't have this problem.
