### ISSUE TITLE
Support cetificate in configure file.

### ISSUE THREAD

**Issue by Rucc1** [trojan-gfw/trojan#62]
```java
 "ssl": {
        "cert": ""
    },
```
only supports external file(file directory), it will be good if trojan can support certs in the configure file, like

```java
  "cert": [
    "-----BEGIN CERTIFICATE-----",
    "exampleCert",
    "-----END CERTIFICATE-----"
  ],
```

**Comment by Chigusa0w0** [comment]
@Rucc1 Personally, I don’t think this proposal will be implemented in view of the following problems.
1. Potential certification management risks. As you may know, Trojan Server requires a valid cert-key pair to work. It would violate the best practice in cert management if we require contents of the key and cert files are written directly into the configuration file. On the other hand, writing the contents of the cert into the configuration file may introduce additional complexity in management.
2. Compatibility and scalability issues. You should be aware that there are multiple certificate file formats, some of which also support extensions. Writing the contents of the certificate directly to the file is not convenient for format conversion if needed, and is not conducive to quickly updating the certificate when needed without affecting the existing configuration - since the users may have modified some section of the configuration file after receiving it.

Your proposal is unlikely to be formally adopted and implemented until the above issues are resolved. But you can fork the project yourself and implement your own version. Regardless, I would like to thank you for your contribution to the Trojan community and wish you a happy Spring Festival.
