### ISSUE TITLE
[Feature request] Implement SIP003 plugin interface

### ISSUE THREAD

**Issue by madeye** [trojan-gfw/trojan#8]
Hi @GreaterFire,

I find this project is quite interesting. It may be necessary to move on to SOCKS5 over TLS in the near future.

I'm wondering if you can implement [SIP003](https://shadowsocks.org/en/spec/Plugin.html) to let your project work with shadowsocks. If so, this project would get supported on all the known platforms and devices instantly.

If you have any question, please let me know.

Thanks,
Max

**Comment by GreaterFire** [comment]
@madeye 
Thank you for your offer. Let me consider this for a while.

**Comment by GreaterFire** [comment]
@madeye

I am very sorry. After due consideration, I am likely not going to implement `SIP003` of trojan for the following reasons:

1. I am still a college student and might not have time (a tough school :) ). Just writing trojan itself has cost me a lot of study time.
2. I am not proficient at C networking programming (which you use as examples).
3. Trojan requires a lot of parameters in the config (see [here](https://greaterfire.github.io/trojan/config)) and I don't know how to integrate them into ShadowSocks (would be a tough work).

However, if you really like this protocol, you can implement it by yourself, because I think the decrypted protocol is pretty much like ShadowSocks (except for the additional hashed password field and `CMD` in the request packet (right now I didn't implement `UDP`, just like ss-libev)) and will be easier for *you* to implement. BTW, trojan is licensed under GPL-v3, so feel free to fork and make any modification to it. I have elaborated on the protocol in my [documentation](https://greaterfire.github.io/trojan/protocol). Also I have another little request :) If you choose to verbatim integrate trojan into ShadowSocks, could you please keep the protocol name `trojan` and list me (GreaterFire \<GreaterFire at protonmail dot com\>) in the contributors list? Thank you very much.

Sorry again for not being able to contribute to ShadowSocks, and thanks again for the offer. I would really love to see trojan being integrated into ShadowSocks but I might not be able to implement it myself.

Feel free to email me or reply to this comment. Hope to see you soon!

Best luck!

**Comment by 0neday** [comment]
I check out trojan code, and I find maybe is difficult to integrate shadowsocks-libev with SIP003 plugin. But we could use trojan forward ss-redir data to ss-server. like [this](https://github.com/trojan-gfw/trojan/issues/514#issuecomment-678306683)?

**Comment by GreaterFire** [comment]
@0neday It's already implemented. I just don't want to document it.

**Comment by 0neday** [comment]
But... this is a weird method to implement SIP003 plugin for shdadowsocks-libev.
